- src/guide/events.md
fix typos in src/guide/events.md
> fix: fix typos

- src/guide/migration/inline-template-attribute.md
- src/guide/migration/introduction.md
> fix: typos

- src/guide/render-function.md
> docs: update jsx repository link

- src/guide/computed.md
- src/guide/introduction.md
- src/guide/template-syntax.md
> fix: add transition link

- README.md
- src/api/directives.md
> fix: fix markdown syntax & reference anchors in api/directives

- src/guide/typescript-support.md
> docs: set jsx as `preserve` in tsconfig.json

- src/cookbook/editable-svg-icons.md
完成文档基础的翻译，水平有限可能存在一些不准确的地方🥺
#21
> Complete translation of editable-svg-icons.md

- src/api/application-config.md
> fix: tweak translation of api/application-config

- src/guide/migration/transition.md
> docs: src/guide/migration/transition.md first commit

- src/guide/component-slots.md
[Issues](https://github.com/vuejs/docs-next-zh-cn/issues/74)
> fix the <span> missing end tag

- src/.vuepress/config.js
> fix: update repo link

- src/guide/migration/array-refs.md
translate `src/guide/migration/array-refs.md`
> docs: src/guide/migration/array-refs.md

- src/guide/composition-api-setup.md
> Review composition-api-setup.md

- src/guide/migration/props-default-this.md
translate `src/guide/migration/props-default-this.md`
> docs: src/guide/migration/props-default-this.md

- src/guide/migration/async-components.md
modified `src/guide/migration/async-components.md`
#98
> docs: modified src/guide/migration/async-components.md

- src/api/global-api.md
> Update global-api.md (fix #100)

- src/guide/migration/functional-components.md
> Update functional-components.md (fix #101)

- src/guide/migration/async-components.md
fix https://github.com/vuejs/docs-next-zh-cn/pull/102#issuecomment-696463177
> Update async-components.md (fix #102)

- src/guide/list.md
> chore: typo

- src/guide/reactivity.md
> chore: single quotation marks 

- src/api/computed-watch-api.md
> fix: fix some links

- src/guide/instance.md
> docs: Typo fix for instance.md

- src/api/application-api.md
> doc: sync doc and tweak translation

- src/guide/events.md
> chore: typos

- src/guide/composition-api-provide-inject.md
> docx:composition-api-provide-inject.md

- src/guide/composition-api-provide-inject.md
Reverts vuejs/docs-next-zh-cn#140
> revert: "docs: composition-api-provide-inject.md"

- src/guide/composition-api-provide-inject.md
- re-merge @GeekQiaQia PR #140
> docs: merge composition-api-provide-inject.md

- src/guide/class-and-style.md
> docs: review class-and-style.md

- src/.vuepress/config.js
- src/.vuepress/theme/components/Navbar.vue
- 恢复 #82 的改动  (代码尽量和原版保持一致)
- 加入 DocSearch 的 config 信息
fix #7
> feat: support docsearch

- src/guide/installation.md
> docs: translate installtion content

- src/guide/mobile.md
translate `src/guide/mobile.md`
#175
> docs: src/guide/mobile.md

- src/guide/migration/introduction.md
repeat item
remove repeat item
> docs: remove repeat item

- src/guide/template-syntax.md
> docs: review src/guide/template-syntax.md

- src/style-guide/README.md
> docs: style-guide/README.md

- src/guide/component-props.md
> docs: component-props.md

- src/guide/migration/global-api-treeshaking.md
> update: src/guide/migration/global-api-treeshaking.md

- src/api/options-api.md
- src/api/options-assets.md
> docs: translate assets

- src/.vuepress/config.js
- src/guide/component-dynamic-async.md
- src/guide/instance.md
- src/guide/migration/key-attribute.md
- src/guide/teleport.md
- 转译 `API Reference`
- 来源 #217
> docs: translate API Reference

- src/guide/component-custom-events.md
更新文档，保持和英文版同步。
详见：[https://github.com/vuejs/docs-next/commit/ec79709fd1b828f6f74069fef7a576ed0528b6f6](https://github.com/vuejs/docs-next/commit/ec79709fd1b828f6f74069fef7a576ed0528b6f6)
> docs: update component-custom-events.md

- src/guide/ssr.md
> docs: ssr.md

- src/guide/transitions-enterleave.md
更新文档。详见[https://github.com/vuejs/docs-next/commit/40e361ff407dfb1b95c79a75d53a0d55810bf087](https://github.com/vuejs/docs-next/commit/40e361ff407dfb1b95c79a75d53a0d55810bf087)
> docs: update transitions-enterleave.md

- src/guide/plugins.md
修改代码错误，变量`i18n`替换为`options`
跟英文版同步。[https://github.com/vuejs/docs-next/commit/29497add8f9007e7cce5900268c743a67720c9c8](https://github.com/vuejs/docs-next/commit/29497add8f9007e7cce5900268c743a67720c9c8)
> docs: update plugins.md

- src/api/refs-api.md
> docs: fix refs-api.md

- src/guide/a11y-standards.md
校对了 /guide/a11y-standard.md
resolve #239
> docs: check translation for /guide/a11y-standards

- src/README.md
> docs: update src/README.md

- src/guide/component-basics.md
> docs: update component-basics.md

- src/api/basic-reactivity.md
修复错误的翻译。
原文是： `Checks if an object is a proxy created by reactive or readonly`
> docs: fix basic-reactivity.md

- src/examples/todomvc.md
更新文档，详见[https://github.com/vuejs/docs-next/commit/1cb74b905826dbe3744c2d782a1e1c17ed606035](https://github.com/vuejs/docs-next/commit/1cb74b905826dbe3744c2d782a1e1c17ed606035)
> docs: update examples/todomvc.md

- src/guide/migration/introduction.md
> docs: fix typo

- src/guide/component-dynamic-async.md
> docs('component-dynamic-async.md'): change suspensable to suspensible

- src/guide/state-management.md
> docs: state-management.md

- src/guide/teleport.md
> docs: fix the translation for "modal"

- src/.vuepress/config.js
Move the migration and contribution guidelines in separate sections 
https://github.com/vuejs/docs-next/pull/699
> fix: update config.js

- src/guide/migration/v-model.md
原文中的 `shorthand for` `shorthand to` 应该是**是以下简写**而不是**简写为**的意思
> `shorthand for` & `shorthand to`

- src/guide/reactivity-computed-watchers.md
问题参考此issues https://github.com/vuejs/docs-next-zh-cn/issues/282
在响应式计算和侦听一节
示例代码：
```js
const count = ref(1)
const plusOne = computed(() => count.value++)
console.log(plusOne.value) // 2
plusOne.value++ // error
```
这个输出的 2 好像并不正确。 输出的是 1。
只有
```js
const plusOne = computed(() => count.value + 1)
console.log(plusOne.value) // 输出的 才是 2.
```
并且英文仓库是
同步英文仓库文档
> update: reactivity-computed-watchers.md  demo

- src/guide/class-and-style.md
> fix: 修改truthy的MDN链接

- src/guide/instance.md
> fix: broken link

- src/guide/instance.md
> fix application-api url is 404

- src/guide/migration/introduction.md
> typo: introduction.md 组建 -> 组件

- src/guide/migration/children.md
docs: src/guide/migration/children.md
#292
> docs: src/guide/migration/children.md

- src/guide/migration/attrs-includes-class-style.md
docs: src/guide/migration/attrs-includes-class-style.md
#295
> docs: src/guide/migration/attrs-includes-class-style.md

- src/guide/migration/listeners-removed.md
docs: src/guide/migration/listeners-removed.md
#297
> docs: src/guide/migration/listeners-removed.md

- src/guide/migration/transition-group.md
docs: src/guide/migration/transition-group.md
#302
> docs: src/guide/migration/transition-group.md

- src/guide/component-basics.md
- src/guide/render-function.md
- [原文](https://github.com/vuejs/docs-next/blob/master/src/guide/component-basics.md) 移除 `new Vue` 的描述
> update: remove new Vue create instance demos

- src/guide/computed.md
> docs: computed.md

- src/guide/reactivity-fundamentals.md
原来的翻译断句错误
```
// 在copy上转换original 会触发侦听器依赖
original.count++
// 转换copy 将导失败并导致警告
copy.count++
```
```
// 通过original修改count，将会触发依赖copy的侦听器
original.count++
// 通过copy修改count，将导致失败并出现警告
copy.count++
```
> fix: reactivity-fundamentals

- src/guide/component-provide-inject.md
[提供 / 注入- 处理响应性](https://v3.cn.vuejs.org/guide/component-provide-inject.html#%E5%A4%84%E7%90%86%E5%93%8D%E5%BA%94%E6%80%A7)的`响应式计算和侦听`链接异常
> fix: component-provide-inject link

- src/guide/migration/emits-option.md
> docs:migration/emits-option.md

- src/api/composition-api.md
Api: getCurrentInstance 未翻译
翻译
> docs : src/api/composition-api.md

- src/guide/component-slots.md
> docs: component-slots.md

- src/guide/migration/v-on-native-modifier-removed.md
docs: src/guide/migration/v-on-native-modifier-removed.md
#299
> docs: src/guide/migration/v-on-native-modifier-removed.md

- src/api/refs-api.md
> fix: fix translation

- src/guide/forms.md
> docs: forms.md

- src/guide/custom-directive.md
指令概念中带上了 `Vue 2.0` 版本号
删掉 `2.0`
概念无关乎版本
> doc: concept has nothing to do with version

- src/guide/component-attrs.md
> docs: component-attrs.md

- src/guide/component-custom-events.md
fix demo code
[emits] is written in methos scope
move up one line
> update: src/guide/component-custom-events.md

- src/api/directives.md
https://github.com/vuejs/docs-next-zh-cn/issues
发现一个指令的错误文档，v-if的优先级应该更高
修复它
无
> review:update the `v-for` and `v-if` priority

- src/guide/ssr.md
中文文档的ssr部分的链接指向的英文链接
将其更改为对应的中文文档链接
> docs: replace english links with chinese links

- src/api/computed-watch-api.md
> fix: add '具有' text

- src/guide/optimizations.md
> Optimizations proofread

- src/guide/installation.md
> docs: update vite app 

- src/.vuepress/config.js
> docs: add a space between & in config.js

- src/guide/migration/introduction.md
> docs: introduction.md

- src/guide/migration/async-components.md
> fix: loadingComponent

- src/guide/component-basics.md
> docs: component-basics.md

- src/guide/migration/async-components.md
- src/guide/migration/custom-directives.md
遗漏 directives created 钩子的介绍，[英文版](https://v3.vuejs.org/guide/migration/custom-directives.html#_2-x-syntax)中有介绍
> [fix] 遗漏 directives created 钩子介绍

- src/api/refs-api.md
> docs: proofread src/api/refs-api.md

- src/guide/introduction.md
update the link of Slot API
The origin link has expired
Change to the new address
> docs: update introduction.md

- src/api/options-lifecycle-hooks.md
>  docs: proofread options-lifecycle-hooks.md

- src/guide/render-function.md
[参照英文文档](https://v3.vuejs.org/guide/render-function.html#v-on)
> update: render-function.md

- src/guide/component-registration.md
> docs: component-registration.md

- src/api/computed-watch-api.md
> Computed watch proofread

- src/guide/component-dynamic-async.md
> docs: component-dynamic-async.md

- src/guide/instance.md
- src/guide/typescript-support.md
> fix: application-api 404 & some translation errors

- src/guide/composition-api-introduction.md
> fix: fix incorrect link

- src/guide/a11y-resources.md
> docs: a11y-resourcecs.md

- src/guide/migration/keycode-modifiers.md
> docs: keycode-modifiers.md

- src/guide/migration/transition.md
> fix: guide/migration/transition

- src/api/instance-properties.md
> Instance properties proofread

- src/guide/reactivity.md
> docs: proofread src/guide/reactivity.md

- src/api/basic-reactivity.md
原文：ref will be unwrapped
更改为ref 会被解构
> fix: fix wrong translation

- src/guide/component-template-refs.md
> fix translation of issue 480

- src/guide/plugins.md
> improve translation

- src/guide/migration/custom-elements-interop.md
> docs: custom-elements-interop.md

- src/guide/a11y-resources.md
1. redundant words
1. delete redundant words
> fix: a11y-resources.md typo

- src/guide/migration/attribute-coercion.md
> docs: attribute-coercion.md

- src/style-guide/README.md
- sync 遗留的 [commit](https://github.com/vuejs/docs-next/blob/7cb38f933b0ff62e1d0568664d16161609c7cd8d/src/guide/list.md)
- fix #466
> fix: v-if in style-guide

- src/guide/typescript-support.md
> fix: 更新链接，旧链接已弃用

- src/api/refs-api.md
英文原文：
If an object is assigned as a ref's value, the object is made deeply reactive by the reactive method.
翻译不准确，不是`可以通过`，而是确定会通过。
> docs: refs-api.md

- src/guide/migration/custom-directives.md
- src/guide/migration/custom-elements-interop.md
- src/guide/migration/data-option.md
完成了 custom-directive.md 剩下的 TODO，还有其他几个文件漏掉的翻译细节。
> docs: translation and fixes

- src/guide/render-function.md
- src/guide/typescript-support.md
- `guide/render-function`
- `guide/typescript`
> Translated new content

- src/.vuepress/public/images/lifecycle.svg
> docs: 翻譯生命週期圖

- src/guide/ssr/build-config.md
- src/guide/ssr/getting-started.md
- translated `ssr/build-config`
- translated `ssr/getting-started`
> Translated some new content about SSR

- src/guide/composition-api-setup.md
> 本指南假定你已经阅读了[组合式 API 简介](composition-api-introduction.html)和[响应性原理](reactivity-fundamentals.html)。如果你不熟悉组合式 API，请先阅读这篇文章。
此处有两篇文章。
本指南假定你已经阅读了[组合式 API 简介](composition-api-introduction.html)和[响应性原理](reactivity-fundamentals.html)。如果你不熟悉组合式 API，请先阅读这两篇文章。
- 注释中的部分英文没有得到翻译，已添加。
> docs: fix typo & add translation in comments

- src/guide/migration/v-model.md
> fix translation error in migration/v-model.md (#557)

- src/guide/migration/introduction.md
outdated version of `eslint-plugin-vue` in [Vue 3 迁移指南/其他项目](https://v3.cn.vuejs.org/guide/migration/introduction.html#%E5%85%B6%E4%BB%96%E9%A1%B9%E7%9B%AE)
> docs: update npm version of eslint-plugin-vue

- src/api/options-composition.md
> update: options-composition.md

- src/guide/composition-api-template-refs.md
> fix: composition-api-template-refs

- src/guide/reactivity.md
与英文文档保持一致
在示例代码中，没有 key 相关源码。在英文文档中，此处是 propery
> bugfix: 修改笔误，将key改成property

- src/guide/reactivity.md
在翻译的时候，未将which这个词翻译出来。alongside 这个词翻译成旁边，感觉太直译了
见commit提交
英文原文：It will check which effect is currently running and record that alongside the target and property
> fix: 未将which这个词翻译出来，并且alongside直译了

- README.md
Added description to encourage people search TODO blocks from source code.
> Edited README to encourage people do translation

- src/api/application-api.md
清理version使用的原文
参见Commit
清除参考部分多余冒号
> fix: 清理版本使用部分英文

- src/api/global-api.md
翻译 createApp 参数部分内容
参见Commit
无
> fix: translate createApp section

- src/api/instance-properties.md
> fix: clean space for see also

- README.md
- Added how to find all translations to do.
- Added how to find all existing sync PRs from English docsite.
> Added more information to README

- src/.vuepress/theme/layouts/404.vue
- src/api/application-config.md
- src/api/options-misc.md
- src/api/special-attributes.md
- 404 template
- `api/application-config`
- `api/options-misc`
- `api/special-attributes`
> Translated some new content

- src/guide/migration/introduction.md
> docs: translate migration-build section

- src/guide/events.md
@Olivia-sun-ye ，Hi，这个 PR 将恢复此前 #559 的改动（具体的原因，见#599、#601）
我们希望你先去给英文版提 PR 来改动，以让整个社区收益。
> docs(revert): events.md

- src/guide/reactivity.md
> fix translation error in guide/reactivity.md

- src/api/global-api.md
> Add a comma to fixed #608

- src/guide/typescript-support.md
> fix(typescript-support): typo "JSF" -> "JSX"

- src/guide/migration/events-api.md
> docs: translate `prop drilling`

- src/guide/migration/keycode-modifiers.md
Description of Problem
翻译按键修饰符页面部分内容并调整部分格式
Proposed Solution
参见Commit
Additional Information
无
> docs: translate TODO section for keycode-modifiers

- src/.vuepress/theme/components/Newsletter.vue
- src/api/options-composition.md
- src/guide/migration/custom-directives.md
- src/guide/migration/introduction.md
- src/guide/reactivity-computed-watchers.md
- src/guide/single-file-component.md
https://github.com/vuejs/docs/compare/9be25f7...7b504b0
> Sync #7b504b0

- src/guide/migration/global-api.md
- src/guide/migration/inline-template-attribute.md
> docs: update

- src/guide/migration/global-api.md
- src/guide/migration/migration-build.md
- `src/guide/migration/global-api.md`
- `src/guide/migration/migration-build.md`
> Translated "migration build" page

- src/guide/migration/inline-template-attribute.md
https://github.com/vuejs/docs-next-zh-cn/pull/630#discussion_r686644394
> Fixed the missing operation of #630

- src/.vuepress/config.js
- src/guide/single-file-component.md
- src/guide/web-components.md
- 更新了一些和英文版不太一致的配置细节
- 修复了侧边栏导航的标题展示问题 (TODO不能放在文章最顶端)
> Updated site config and fixed title in side nav

- src/guide/migration/array-refs.md
- src/guide/migration/async-components.md
- src/guide/migration/attribute-coercion.md
- src/guide/migration/attrs-includes-class-style.md
- src/guide/migration/children.md
- src/guide/migration/custom-directives.md
- src/guide/migration/custom-elements-interop.md
- src/guide/migration/data-option.md
- src/guide/migration/events-api.md
- src/guide/migration/filters.md
- src/guide/migration/functional-components.md
- src/guide/migration/global-api.md
- src/guide/migration/inline-template-attribute.md
- src/guide/migration/keycode-modifiers.md
- src/guide/migration/listeners-removed.md
- src/guide/migration/mount-changes.md
- src/guide/migration/props-default-this.md
- src/guide/migration/render-function-api.md
- src/guide/migration/slots-unification.md
- src/guide/migration/transition-group.md
- src/guide/migration/v-bind.md
- src/guide/migration/v-if-v-for.md
- src/guide/migration/v-model.md
- src/guide/migration/v-on-native-modifier-removed.md
- src/guide/migration/vnode-lifecycle-events.md
- src/guide/migration/watch.md
> migration build flag -> 迁移构建开关

- src/guide/component-registration.md
> docs: Update component-registration.md

- src/.vuepress/components/guide/contributing/translations-data.js
> docs: update translations-data.js

- src/api/computed-watch-api.md
> docs: update computed-watch-api.md

- src/api/sfc-script-setup.md
translated sfc-script-setup.md file
> docs: translate sfc-script-setup.md

- src/guide/migration/array-refs.md
> docs: Update array-refs.md

- src/api/sfc-tooling.md
> docs: minor improvements for src-tooling

- src/api/sfc-script-setup.md
> review-sfc-script-setup

- src/guide/reactivity-computed-watchers.md
First translate for section Computing Debugging
None
None
> docs: update reactivity-computed-watchers.md

- src/guide/migration/functional-components.md
> update functional-components.md 

- src/guide/migration/custom-elements-interop.md
> docs: Update custom-elements-interop.md

- src/guide/migration/vnode-lifecycle-events.md
> docs: Fix style issues

- src/guide/mixins.md
- src/guide/render-function.md
> Fix two origin comments

- src/guide/web-components.md
接https://github.com/vuejs/docs-next-zh-cn/pull/730 ，合并了wxsms的建议
> docs: new translate web-components.md

- src/api/sfc-spec.md
> review: sfc-spec

- src/.vuepress/components/community/team/emeriti.js
- src/.vuepress/components/community/team/members.js
- src/api/special-attributes.md
- src/guide/component-custom-events.md
- src/guide/migration/attribute-coercion.md
- src/guide/migration/key-attribute.md
- src/guide/web-components.md
https://github.com/vuejs/docs/compare/b8c599f...20e3ae6
> sync #20e3ae6

- src/guide/web-components.md
> docs: update web-components.md

- src/guide/migration/global-api.md
> docs(zh-cn): translated some words

- src/api/built-in-components.md
https://github.com/vuejs/docs/compare/ce2c8dd...c98b5a4
> sync #c98b5a4

- src/api/sfc-spec.md
- src/guide/composition-api-lifecycle-hooks.md
- src/guide/composition-api-provide-inject.md
- src/guide/introduction.md
- src/guide/reactivity-fundamentals.md
- src/guide/ssr/routing.md
- src/guide/ssr/server.md
- src/guide/ssr/structure.md
https://github.com/vuejs/docs/compare/c98b5a4...210b792
> sync #210b792

- src/api/sfc-tooling.md
- src/cookbook/debugging-in-vscode.md
- src/guide/ssr/structure.md
https://github.com/vuejs/docs/compare/210b792...d026fc2
> sync #d026fc2

- src/api/built-in-components.md
- src/guide/migration/custom-elements-interop.md
- src/guide/ssr/routing.md
https://github.com/vuejs/docs/compare/d026fc2...563ed27
> sync #563ed27

- src/.vuepress/components/community/team/partners.js
- src/api/directives.md
- src/api/sfc-script-setup.md
- src/guide/component-basics.md
- src/guide/component-props.md
- src/guide/component-registration.md
- src/guide/component-slots.md
- src/guide/forms.md
- src/guide/single-file-component.md
https://github.com/vuejs/docs/compare/563ed27...c90a0a2
> sync #c90a0a2

- src/api/special-attributes.md
https://v3.cn.vuejs.org/api/special-attributes.html#is
> review:correct translation errors

- src/.vuepress/components/guide/contributing/translations-data.js
- src/guide/composition-api-introduction.md
- src/guide/transitions-overview.md
https://github.com/vuejs/docs/compare/b596073...28b17da
skipped: https://github.com/vuejs/docs/commit/131fcf0fc6e52cf9cc81a7f08c8c4a847ab191f8
also resolved: https://github.com/vuejs/docs-next-zh-cn/pull/829#issuecomment-984385658
> sync #28b17da

- src/.vuepress/components/community/themes/theme-data.js
- src/guide/installation.md
- src/guide/migration/migration-build.md
https://github.com/vuejs/docs/compare/4dfc045...0fd3fff
> sync #0fd3fff

- src/guide/composition-api-setup.md
- src/guide/custom-directive.md
https://github.com/vuejs/docs/compare/0c0b6f0...ba5586e
> sync #ba5586e

- src/guide/data-methods.md
34行“你应该避免使用这两个字符开头的的顶级 `data` property 名称”多出一个“的”
34行“你应该避免使用这两个字符开头的的顶级 `data` property 名称”多出一个“的”
> 34行“你应该避免使用这两个字符开头的的顶级 `data` property 名称”多出一个“的”

- src/guide/contributing/writing-guide.md
> docs(cn): update src/guide/contributing/writing-guide.md

- src/guide/computed.md
> change '已经' to '以'

- src/guide/transitions-enterleave.md
> change '过度' to '过渡'

- src/guide/migration/introduction.md
Fix https://github.com/vuejs-translations/docs-zh-cn/issues/343
> Fixed broken CodeSandbox link

- src/api/sfc-script-setup.md
> fix: Typescript -> TypeScript
