vuejs/docs-next-zh-cn

src/guide/instance.md

很高兴终于有中文文档了！！！晚上看到一处斜体解析错误，英文版本是单词，下划线两端是空格，所以能正确解析。
依据[关于加粗和斜体格式的约定](https://github.com/vuejs/docs-next-zh-cn/wiki/%E6%9C%AF%E8%AF%AD%E7%BF%BB%E8%AF%91%E7%BA%A6%E5%AE%9A#%E5%85%B3%E4%BA%8E%E5%8A%A0%E7%B2%97%E5%92%8C%E6%96%9C%E4%BD%93%E6%A0%BC%E5%BC%8F%E7%9A%84%E7%BA%A6%E5%AE%9A)，修正为星号斜体。

fix: italic style

---

src/guide/teleport.md

fix: delete original English

---

src/guide/transitions-enterleave.md

update `src/guide/transitions-enterleave.md`

chore: update transitions-enterleave.md

---

src/api/global-api.md

`h` 方法的第一个参数名称是`type`不再是`tag`。英文版PR已经merged : https://github.com/vuejs/docs-next/pull/450

fix: rename `tag` to `type`

---

src/.vuepress/theme/components/Navbar.vue

- [fix: the isAlgoliaSearch variable set to boolean type](https://github.com/vuejs/docs-next/pull/519)
- 修复 native searchBox， 英文仓库已经merge，本次直接并入master

fix: native searbox work when disabled algolia

---

src/guide/render-function.md

Mostly in "h() Arguments" chapter. Details:
- Typo: `attributy` → `attribute`
- Removed one English line.
- Translated one line.
- Few Chinese-English spacing issues.
- Added a few missing period marks.

fix: a typo & few minor things

---

src/guide/migration/global-api.md

src/guide/migration/global-api.md  `Vue.使用` 修改为 `Vue.use`  #95

docs: update src/guide/migration/global-api.md

---

src/guide/migration/global-api.md

修改全局api provide的代码用例，
保持和[https://github.com/vuejs/docs-next/blob/master/src/guide/migration/global-api.md#provide--inject](https://github.com/vuejs/docs-next/blob/master/src/guide/migration/global-api.md#provide--inject)一致
修复https://github.com/vuejs/docs-next-zh-cn/issues/106

fix: change global-api provide

---

src/api/application-api.md
src/guide/migration/key-attribute.md

chore: typos

---

src/guide/reactivity-fundamentals.md

docs-next-zh-cn/src/guide/reactivity-fundamentals.md 
该对象作为它的内部值——一个**响应式的引用** 
markdown 格式错误修复。

fix: typos

---

src/guide/migration/global-api.md

fix: invalid link and typos

---

src/guide/installation.md

fix: incoherent translation of terms

---

src/api/application-config.md

移除devtools
保持和https://github.com/vuejs/docs-next/blob/master/src/api/application-config.md 一致。

fix: remove devtools from config

---

src/guide/composition-api-lifecycle-hooks.md

docs: composition-api-lifecycle-hooks.md

---

src/guide/migration/global-api.md

[#150](https://github.com/vuejs/docs-next-zh-cn/issues/154)

docs: global-api.md

---

package.json
src/.vuepress/components/VideoLesson.vue
src/.vuepress/styles/index.styl
src/guide/component-custom-events.md
src/guide/composition-api-introduction.md
src/guide/reactivity.md

- 添加 videoLession，原英文仓库：
- hash：[8d8d190](https://github.com/vuejs/docs-next/commit/8d8d19042ebf18110cf08fa8d10ad977f3fd5e82#diff-b99e5d7e651f9c3cf34f7ed89af10943)
- commit: [docs: update video styles (#495)](https://github.com/vuejs/docs-next/commit/8d8d19042ebf18110cf08fa8d10ad977f3fd5e82#diff-b99e5d7e651f9c3cf34f7ed89af10943)
- 其中一项（src/guide/composition-api-lifecycle-hooks.md）已在#148 中得到更新

docs: add migration videoLesson

---

src/guide/conditional.md

阅读 英文文档 的 [列表渲染](https://v3.vuejs.org/guide/list.html#v-for-with-v-if) 发现 v-for 和 v-if 发生了重大变化，中文文档没有提及
> When they exist on the same node, v-if has a higher priority than v-for. That means the v-if condition will not have access to variables from the scope of the v-for
按照原文进行修正

docs: update the `v-for v-if` priority

---

src/guide/component-template-refs.md

The original translation was weird... And I noticed that the original content is nearly identical to the v2 version. So I copied the v2 translation with a minor change:
* "子组件" → "子元素", since I feel "元素" is more general than "组件", considering `$refs` works on both DOM elements and components.

docs: reword warning section

---

src/guide/composition-api-provide-inject.md

在父组件 MyMap.vue 中 provide 的是 provide('updateLocation', updateLocation)，所以子组件中应该 inject updateLocation，但原文却是 const updateUserLocation = inject('updateUserLocation')
将 updateUserLocation 改为 updateLocation

fix: modify the error in the sample code

---

src/guide/composition-api-introduction.md

在 `guide/composition-api-introduction.md` 中，抽取独立的组合函数部分，第一个 `useUserRepositories.js` 文件中多导入了 `toRefs` 函数，第二个 `useRepositoryNameSearch.js` 文件中多导入了 `onMounted, watch, toRefs` 函数，且少导入了 `computed` 函数。
修正导入的函数。
英文仓库没有这些问题，本次提交直接参考英文仓库进行修改的。

fix: modify the error in the sample code.

---

src/api/application-api.md

docs: application-api.md

---

src/.vuepress/config.js

当前生成的站点的语言信息是 `<html lang="en-US">`
修复之后是 `<html lang="zh-CN">`

fixed the locale config

---

package.json
patches/@vuepress+core+1.6.0.patch
yarn.lock

修复中文标题定位和滚动时的报错
通过 `patch-package` 临时修复了 vuepress 中的问题。后续 vuepress 如果更新之后，这个 patch 可以随时再去掉。
#5 
另外我发现本地开发模式下和最终 build 出来的版本在行为上有差异。本地开发模式下滚动和锚点定位依然有问题，但最终 build 出来是正常的。

Fixed scroll bugs at encoded title 

---

src/guide/data-methods.md

docs: src/guide/data-methods.md
#200

docs: src/guide/data-methods.md

---

src/guide/component-slots.md

从示例要表达的意思看，是要表达匿名插槽和具名插槽的作用域不能混用。黄框示例内todo-list嵌套todo-list后，与红框示例对比产生了歧义。
如果是的话，英文版文档似乎也存在该问题，如果理解错误，还请指正。谢谢
将黄框内的 todo-list 替换为 template，修改为如下内容

docs: update component-slots.md

---

src/api/built-in-components.md
src/api/global-api.md
src/api/instance-methods.md
src/api/instance-properties.md
src/api/options-data.md
src/api/options-dom.md
src/api/options-lifecycle-hooks.md
src/api/refs-api.md
src/api/special-attributes.md
src/guide/component-custom-events.md
src/guide/component-slots.md
src/guide/composition-api-template-refs.md
src/guide/forms.md
src/guide/migration/v-model.md
src/guide/state-management.md

v3中文文档部分超链接指向的英文标题，不能跳转到对应的章节。
将markdown锚点修复为中文标题。

docs: fix markdown anchor

---

src/guide/mixins.md

[混入-选项合并](https://v3.cn.vuejs.org/guide/mixins.html#%E9%80%89%E9%A1%B9%E5%90%88%E5%B9%B6)的`console.log`可统一为中文。同[v2 - 混入-选项合并](https://cn.vuejs.org/v2/guide/mixins.html#%E9%80%89%E9%A1%B9%E5%90%88%E5%B9%B6)

fix: mixins typo

---

src/guide/composition-api-setup.md

翻译：当解构可选的props属性时，当可选属性未传入而需解构该属性时，使用 toRef 代替 toRefs

update: translate composition-api-setup.md

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/default.md

根据讨论，添加了两个 `issue template`:
1. bug report template，适用于文档纠错
2. default template, 适用于任意格式
bug report template:
（其他补充：如果可以的话，有中英双语可能会更加恰当）
@jinjiang @Justineo 
另外，英文主站，已添加了中文站点入口：v3.vuejs.org

feat: add github issue template

---

src/guide/component-custom-events.md

update: src/guide/component-custom-events.md

---

src/api/computed-watch-api.md

fix: add '执行' text

---

src/guide/render-function.md

keep the same with https://github.com/vuejs/docs-next/pull/803.

docs: Use destructuring to access createApp render-function.md

---

src/guide/change-detection.md

docs: proofread src/guide/change-detection.md

---

src/guide/component-template-refs.md

- fix #357 
- 英文相关 issue [Arrays in $refs](https://github.com/vuejs/docs-next/issues/400)
- 英文相关 [commit](https://github.com/vuejs/docs-next/commit/8abb7eebd90bd9f4c60132cb0ac34306265b8a1c#diff-adeb11e65b68bf49c586fb5898c40aa271d048bb6b7da4526a4cb32e489e382f)

fix: removed v-for for refs, close #357

---

src/api/directives.md

fix: fix the translation of v-if used with v-for

---

src/api/global-api.md

`resolveComponent(component)`未找到返回的应该是传入的参数`component`而非`undefined`。 
源码： https://github.com/vuejs/vue-next/blob/82bf7ebf36833679f13039e5b0282eff2859e18f/packages/runtime-core/src/helpers/resolveAssets.ts#L20

[fix] 修正resolveComponent未找到返回的值

---

src/guide/composition-api-setup.md

Tab used as code style indent in [composition-api-setup guide](https://v3.cn.vuejs.org/guide/composition-api-setup.html#props), cause in inconsistency code style.
Replace tab using 2 space.
https://github.com/vuejs/docs-next/pull/858

doc: fix composition-api-setup code indent

---

src/api/composition-api.md

[有歧义的地址链接](https://v3.cn.vuejs.org/api/composition-api.html#setup)
英文文档中的原句是：
```
To get type inference for the arguments passed to setup(), the use of defineComponent is needed.
```
中文文档中翻译的是：
```
若要获取传递给 setup() 的参数的类型推断，请使用 defineComponent 是需要的。
```
翻译后的句子存在语句不通顺的问题，联系上下文可以使用
```
在 defineComponent 中通过 setup function 定义组件时，可以通过定义传递参数的类型进行类型推断
```

docs(composition-api): 修正composition-api翻译错误

---

src/guide/typescript-support.md

英文：For example, if you have a component with a number count property, you will have an error if you try to call a string-specific method on it:
现有翻译指代混乱，这里应该指代的是数字类型的 count property 而不是拥有这个 property 的组件。另外前后两个”如果“连着用，读起来很拗口。
于是调整了语言组织，读起来更顺口，也更”白话“一些。

docs: 更好的语言组织

---

src/guide/component-slots.md

./src/guide/component-slots.md 
line 277
原来写的是：
绑定在 `<slot` > 元素上的 attribute 被称为插槽 prop。
改成了
绑定在 `<slot>` 元素上的 attribute 被称为插槽 prop。
无

docs: fix a tiny markdown grammar mistake

---

src/api/directives.md

修复v-html 中 CSS Modules 的链接为中文，与useCssModule处 CSS Modules 的链接保持一致

docs: fix the link to CSS Modules in directives

---

src/api/basic-reactivity.md

在响应式基础 API 中，一些 `unwrap` 翻译为解构应该是不准确的，用解包也许更恰当。
#487

docs: fix some unwrap translate

---

src/api/options-composition.md
src/guide/composition-api-setup.md
src/guide/reactivity-fundamentals.md

#487 看到该 issue 同步的结论，全局搜索文档中的`解构`，觉得翻译合理，无需再修改。
全局搜索官方文档中的 `unwrap` ，逐个修正未翻译为 `解包` 的部分。

docs: fix unwrap translate

---

src/guide/transitions-list.md

Review transitions-list.md #115

---

src/guide/migration/introduction.md

fix: link error

---

src/guide/reactivity.md

直译存在笔误：将`and runs them` 翻译成 `并执行它们`，而不是`和它们的执行`，
英文原文：Re-run the code that read the value originally: the trigger function looks up which effects depend on the property and runs them.

fix: 解决直译笔误

---

src/guide/reactivity-fundamentals.md

nested 是修饰property，不是修饰object，翻译翻错位置了
见Commit
英文原文：The reactive conversion is "deep" - it affects all nested properties of the passed object.

fix: 定语翻译错位置

---

src/guide/events.md

可能引起的歧义问题：
此前的表述：" Alt 或 Shift 被一同按下 "，可能会被误解为：忽略Ctrl被按下的事实而进行其他按键的组合
见 commit

fix: 解决可能引起的歧义问题

---

src/guide/migration/global-api.md

`we strongly recommend favoring composition via [Composition API] over...` 这一段不知道 `favoring composition` 应该怎么翻译，所以直接翻译为了 `强烈建议使用 [组合式 API] 来替代...`，感觉也算通顺。

docs: translate global-api.md

---

src/api/application-api.md

如果不传入 definition 参数 (第二个 component 参数)，返回组件定义。
```ts
export declare interface App<HostElement = any> {
// ...
component(name: string): Component | undefined;
component(name: string, component: Component): this;
// ...
}
```

docs: fix application-api.md

---

src/guide/component-custom-events.md

子组件中，`emits` 选项为在组件上定义”发出“的事件，而非”已发出“的事件，此处的形容词”已“容易带来歧义。同时，本文其他地方也均采用的是”发出“而非”已发出“。
建议替换”已发出“为”发出“

fix: remove incorrect word

---

src/.vuepress/config.js
src/.vuepress/theme/components/Page.vue
src/.vuepress/theme/components/PageEdit.vue

editLinks 设置为了 true，但组件被注释掉了，导致并没有出来。去掉了注释，并且翻译了里面的文字。
并且同步了我为原版文档提交的内容，见 https://github.com/vuejs/docs/pull/1182

feat: enable edit link

---

src/guide/template-syntax.md

先前的`错误的值`的描述可能会令人有所迷惑,用 falsy 比较准确 也和前面的 truthy 统一

Fix: 用 falsy 并且添加维基链接来代替 '错误的值' 这一描述

---

src/guide/component-attrs.md

fallthrough 翻译不恰当 回退应该是fallback    data-status的短横杠缺失  data-status是attribute 而不是 property
fallthrough 翻译成贯穿 data-status是attribute 而不是 property 在 Update component-attrs.md #1183  merge进英文版了

fix:修改关于fallthrough的翻译,标点缺失,同步英文版修改

---

src/api/sfc-style.md

docs: translate sfc-style.md

---

src/guide/single-file-component.md

Translated single file component

---

src/guide/introduction.md
src/guide/reactivity-computed-watchers.md
src/guide/web-components.md

- `src/guide/introduction.md`
- `src/guide/reactivity-computed-watchers.md`

Translated some new guide content

---

src/api/effect-scope.md
src/api/global-api.md
src/api/reactivity-api.md
src/api/sfc-spec.md
src/api/sfc-tooling.md
src/guide/web-components.md

- `src/api/effect-scope.md`
- `src/api/global-api.md`
- `src/api/reactivity-api.md`

Translated some new content in src/api/

---

src/guide/component-basics.md

去除模糊不清的`应该可以`的表述，可能会导致读者迷惑。
虽然我查阅了英文版本的描述`Now v-model should work perfectly with this component:`，也有should的表述。
如果是确定无疑的事情，我认为是可以删除的，否则最好能给出特例解释。

去除component-basics文档中“应该可以”的表述

---

src/guide/migration/custom-elements-interop.md

- 相关的pr https://github.com/vuejs/docs/pull/1197

docs: Update custom-elements-interop.md

---

src/guide/migration/v-bind.md

-   相关的PR https://github.com/vuejs/docs/pull/1198

docs: Update v-bind.md

---

src/guide/teleport.md

读文档的时候感觉这个地方不通顺，可以更信雅达
原文：This also means that injections from a parent component work as expected, and that the child component will be nested below the parent component in the Vue Devtools, instead of being placed where the actual content moved to.

Polish up translation to avoid ambiguity

---

.github/workflows/nodejs.yml

the repo has yarn.lock, but no package-lock.json. so yarn should be used in CI.

ci: use yarn

---

src/guide/migration/transition-group.md

- 相关的PR https://github.com/vuejs/docs/pull/1237

docs: Update transition-group.md

---

src/guide/migration/introduction.md

- 相关的PR https://github.com/vuejs/docs/pull/1236

docs: Update introduction.md

---

package.json
scripts/sync.js
yarn.lock

（基于目前同步代码的提交格式是 `sync #xxx` 的前提，能节省大家一点点的时间）
添加了一个简单的脚本，能够自动找到历史记录中最近的 `sync #xxx` 格式提交，并以它为起点，打开浏览器与最新的 vuejs/docs 的 master 分支进行比对。
使用方法：
```
npm run sync
```
这将打开：https://github.com/vuejs/docs/compare/b8c599f...master

feat: sync script

---

src/api/refs-api.md

- reactive 是个函数 而不是方法   https://github.com/vuejs/docs/pull/1199
-  ` toRefs `  和 ` toRef `  只能用在  **reactive**  对象上, **ref**  对象也是**响应式**对象 用不了这两个函数
-  解构/展开是 destructure/spread  更精确的称呼
-   effect根据 #657 保留effect本身

docs: Update refs-api.md

---

src/guide/migration/custom-elements-interop.md

See `在 Vue 3.0 中，此检查在模板编译期间执行。`,

docs: Fix doc typo mistake

---

src/style-guide/README.md

“在单文件组件中，有内容的组件应该是自闭合的” ，这句话的意思与下面紧跟的例子完全相反。
应改为：“在单文件组件中，没有内容的组件应该是自闭合的”

关于风格指南（src/style-guide/README.md ）的 “自闭合组件” 中的问题

---

src/guide/installation.md

npm.taobao.org 域名已经更新为 npmmirror.com
See https://zhuanlan.zhihu.com/p/430580607

Use npmmirror.com instead of npm.taobao.org

---

src/guide/reactivity.md

chore: 将”严等于“替换为”严格等于“

---

src/guide/reactivity-fundamentals.md

原文 `when we have a provided reactive object, we want to prevent mutating it where it's injected.` 的意思，应该是说一个 `provide` 响应式对象在被 `inject` 到子组件之后，不希望这个响应式对象被子组件改变（单向数据流思想）。
原翻译 `我们不想让它在注入的时候被改变` 感觉对应的是 `we want to prevent mutating it where it's injecting`。所以**注入的时候**应该不会被改变，而是注入之后被子组件某个操作改变。更改为 `我们不想让它在注入之后被改变` 更合理
个人愚见，如有误解望各位雅正。

Update the translation of `where it's injected`
